### ISSUE TITLE
What changes need to be done to train on custom dataset?

### ISSUE THREAD

**Issue by sheetalsh456** [eliorav/writing-style-transfer#1]
Hey,
I have a custom dataset wherein I have some text data in the X domain and some in the Y domain in the form of text files. I want to train this model on my custom dataset. Can you please tell me what changes need to be done to incorporate this?

**Comment by eliorav** [comment]
Hi, 
All you need to do is to put your data into `.data` folder and update the value of `DATASET_NAME` in the constants file.
the result should be something like: 
```
DATASET_NAME = 'your_dataset_folder'
```
In addition, you need to specify the file extension for each domain, to do so modify the relevant values in the constants file:
```
POSITIVE_FILE_EXTENSION = '.domain_a'
NEGATIVE_FILE_EXTENSION = '.domain_b'
```
note that you need to split the data to test/train/val files.

best,
Elior
